version: "3.3"

networks:

    khyber:

        external: true

        # driver: bridge

volumes:

    timescaledb:

        external: true

services:

    traccar:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "8082:8082"
            - "5055:5055"
            - "5179:5179"

        container_name: traccar

        volumes:
            - ./traccar.xml:/opt/traccar/conf/traccar.xml

        # image: traccar/traccar:4.15

        build: .

        depends_on:
            - timescaledb

    timescaledb:

        restart: unless-stopped

        networks:
            - khyber

        container_name: timescaledb

        volumes:
            - "timescaledb:/var/lib/postgresql/data"

        image: timescale/timescaledb:2.5.1-pg13

        env_file:
            - timescaledb.env
