version: "3.3"

networks:

    khyber:

        external: true

        # driver: bridge

volumes:

    postgresql:

        external: true

services:

    traccar:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "8082:8082"
            - "5055:5055"
            - "5179:5179"

        container_name: traccar

        volumes:
            - ./traccar.xml:/opt/traccar/conf/traccar.xml

        # image: traccar/traccar:4.15

        build: .

        depends_on:
            - postgresql

    postgresql:

        restart: unless-stopped

        networks:
            - khyber

        container_name: postgresql

        volumes:
            - "postgresql:/var/lib/postgresql/data"

        image: postgres:12

        env_file:
            - postgresql.env
