version: "3"

services:

    web:

        restart: unless-stopped

        ports:
            - "8069:8069"

        volumes:
            - "odoo-web-data:/var/lib/odoo"
            - "./config:/etc/odoo"
            - "./addons:/mnt/extra-addons"

        image: odoo:14.0

        environment:
            - PASSWORD_FILE=/run/secrets/postgresql_password

        secrets:
            - postgresql_password

        depends_on:
            - db

    db:

        volumes:
            - "odoo-db-data:/var/lib/postgresql/data/pgdata"

        image: postgres:13

        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
            - POSTGRES_USER=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata

        secrets:
            - postgresql_password

volumes:

    odoo-web-data:

    odoo-db-data:

secrets:

    postgresql_password:

        file: odoo_pg_pass
