version: "3"

services:

    odoo-postgresql:

        restart: unless-stopped

        # networks:
            # - khyber

        container_name: odoo-postgresql

        volumes:
            - "odoo-postgresql:/var/lib/postgresql/data"

        image: postgres:14

        env_file:
            - postgresql.env

    odoo:

        restart: unless-stopped

        ports:
            - "8069:8069"

        volumes:
            - "odoo:/var/lib/odoo"
            - "./config:/etc/odoo"
            - "./addons:/mnt/extra-addons"

        image: odoo:14.0

        env_file:
            - odoo.env

        depends_on:
            - odoo-postgresql

volumes:

    odoo-postgresql:

    odoo:
