version: "3"

networks:

    khyber:

        external: true

        # driver: bridge

volumes:

    timescaledb:

        external: true

    node-red:

        external: true

    mosquitto:

        external: true

services:

    traccar:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "8082:8082"
            - "5055:5055"
            - "5179:5179"

        container_name: traccar

        volumes:
            - "./traccar.xml:/opt/traccar/conf/traccar.xml"

        image: irasus_traccar

        depends_on:
            - timescaledb

    timescaledb:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        container_name: timescaledb

        volumes:
            - "timescaledb:/var/lib/postgresql/data"

        image: timescale/timescaledb:2.5.1-pg13

        env_file:
            - timescaledb.env

    mosquitto:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1883:1883"

        container_name: mosquitto

        volumes:
            - "mosquitto:/mosquitto/"

        image: eclipse-mosquitto

    node-red:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1880:1880"

        container_name: node-red

        volumes:
            - "node-red:/data"

        image: nodered/node-red:2.2.0

        depends_on:
            - timescaledb
            - mosquitto
