version: "3"

networks:

    khyber:

        external: true

        # driver: bridge

volumes:

    # grafana:

        # external: true

    timescaledb:

        external: true

    node-red:

        external: true

    mosquitto:

        external: true

services:

    postgrest:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "3000:3000"

        container_name: postgrest

        image: postgrest/postgrest:v9.0.0

        depends_on:
            - timescaledb

        env_file:
            - postgrest.env

    flyway:

        restart: on-failure

        networks:
            - khyber

        container_name: flyway

        command: migrate

        volumes:
            - "./flyway/sql:/flyway/sql"
            - "./flyway/conf:/flyway/conf"

        image: flyway/flyway:8.4.4-alpine

        depends_on:
            - timescaledb

    traccar:

        restart: unless-stopped

        networks:
            - khyber

        ports:
            - "8082:8082"
            - "5055:5055"
            - "5179:5179"

        container_name: traccar

        volumes:
            - "./traccar.xml:/opt/traccar/conf/traccar.xml"

        image: irasus/traccar:22.02

        depends_on:
            - flyway

    timescaledb:

        restart: unless-stopped

        # network_mode: host

        # ports:
            # - "5432:5432"

        networks:
            - khyber

        container_name: timescaledb

        volumes:
            - "timescaledb:/var/lib/postgresql/data"

        image: timescale/timescaledb:2.5.1-pg13

        env_file:
            - timescaledb.env

    mosquitto:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1883:1883"

        container_name: mosquitto

        volumes:
            - "mosquitto:/mosquitto/"

        image: eclipse-mosquitto:2.0.14

    node-red:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1880:1880"

        container_name: node-red

        volumes:
            - "node-red:/data"

        image: nodered/node-red:2.2.0

        environment:
            - TZ=Asia/Kolkata

        depends_on:
            - timescaledb
            - mosquitto
