version: "3"

networks:

    khyber:

        external: true

        # driver: bridge

volumes:

    node-red:

        external: true

    mosquitto:

        external: true

services:

    mosquitto:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1883:1883"

        container_name: mosquitto

        volumes:
            - "mosquitto:/mosquitto/"

        image: eclipse-mosquitto

    node-red:

        restart: unless-stopped

        # network_mode: host

        networks:
            - khyber

        ports:
            - "1880:1880"

        container_name: node-red

        volumes:
            - "node-red:/data"

        image: nodered/node-red:2.2.0

        depends_on:
            # - postgresql
            - mosquitto
