version: "3"

networks:

    khyber:

        external: true

        # driver: bridge

volumes:

    mariadb:

        external: false

services:

    mariadb:

        image: mariadb:10.4

        networks:
            - khyber

        ports:
            - "3306:3306"

        volumes:
            - "mariadb:/var/lib/mysql"

        env_file:
            - mariadb.env

    steve:

        build: .

        # image: irasus/steve:latest

        networks:
            - khyber

        volumes:
            - ".:/code"

        ports:
            - "8180:8180"
            - "8443:8443"

        depends_on:
            - mariadb
